workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^gl-/ && $CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH == "mcr/staging"'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH == "mcr/release"'
    - when: never

stages:
  - verify
  - test
  - github-sync
  - gitlab-release
  - gitlab-cleanup

include:
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/rustc/verify.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/rustc/test.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/github/validate.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/github/push.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/gitlab/validate.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/gitlab/release.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/rustc/release-build.yml'
  - project: '${GL_CICD_SHARED_PROJ}'
    ref: main
    file: '/gitlab/cleanup.yml'

variables:
  GH_RELEASE_PUSH: 'true'
  GH_FORCE_PUSH: 'true'
  GH_PUBLIC_REPO: 'true'
  GL_CLEAR_GLAB: 'false'
  GL_RELEASE_ASSET: 'false'
  APPEND_VERSION: 'true'
  RELEASE_VERSION: '0.3.44'
  APPLY_PATCHES: 'true'
  APPLY_PATCHES_EXCLUDE: ''
  GL_CICD_RUNNER_BUILD: '${GL_CICD_RUNNER_RUST}'
  GL_CICD_RUNNER_RELEASE: '${GL_CICD_RUNNER_GLAB}'
  GL_RELEASE_TARGET: 'x86_64-unknown-linux-gnu'
  GL_RELEASE_CARGO_MANIFEST: 'Cargo.toml'
  GL_RELEASE_ARTIFACT_PREFIX: 'regreet'
  GL_RELEASE_PACKAGE_NAME: 'regreet'
  GL_RELEASE_CARGO_EXCLUDES: ''
  RELEASE_BINS: |
    regreet

gl_release_build_asset:
  script:
    - !reference [.github_version_prepare, script]
    - !reference [.github_release_patch_helpers, script]
    - !reference [.gitlab_release_prepare, script]
    - !reference [.rustc_release_asset_build, script]
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y
    - apt-get install -y --no-install-recommends libgtk-4-dev libglib2.0-dev
    - rm -rf /var/lib/apt/lists/*
    - /bin/bash /tmp/rustc_release_build.sh
