name: Release regreet

on:
  workflow_run:
    workflows: ["Build regreet"]
    types: [completed]

permissions:
  contents: write
  actions: write

jobs:
  release:
    name: Create GitHub release (linux)
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'gl-regreet-v')
    uses: mattycramer/gh-actions/.github/workflows/release-from-workflow-run.yml@7229a9e4835f635f77a95eaace0be43cbba6a12f
    with:
      tag: ${{ github.event.workflow_run.head_branch }}
      tag_prefix: gl-regreet-v
      allow_revision_suffix: true
      run_id: ${{ github.event.workflow_run.id }}
      artifact_prefix: regreet-x86_64-unknown-linux-gnu-
      tarball_prefix: regreet-x86_64-unknown-linux-gnu-
      checksum_prefix: regreet-sha256-checksums-
      release_name: regreet v{version}
    secrets: inherit
